# Generated by Django 4.2.3 on 2023-07-22 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.curso')),
            ],
            options={
                'db_table': 'matriculas',
            },
        ),
        migrations.CreateModel(
            name='MateriaDoCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.materia')),
            ],
            options={
                'db_table': 'Matérias dos cursos',
            },
        ),
    ]
