# Generated by Django 3.2.20 on 2023-08-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissaoRealizarProva',
            new_name='Permissioes',
        ),
        migrations.AlterModelOptions(
            name='permissioes',
            options={'permissions': [('podeFazerProvas', 'aluno pode realizar a prova'), ('ehAdministrador', 'usuário logado é administrador')]},
        ),
    ]
