# Generated by Django 4.2.3 on 2023-07-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('materia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ava.materia')),
            ],
            options={
                'db_table': 'provas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rotaDoAnexo', models.CharField(max_length=255)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.materia')),
            ],
            options={
                'db_table': 'materiais',
            },
        ),
    ]
