# Generated by Django 3.2.20 on 2023-07-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=255)),
                ('alternativa1', models.CharField(max_length=255)),
                ('alternativa2', models.CharField(max_length=255)),
                ('alternativa3', models.CharField(max_length=255)),
                ('alternativa4', models.CharField(max_length=255)),
                ('alternativaCorreta', models.IntegerField()),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.prova')),
            ],
            options={
                'db_table': 'questoes',
            },
        ),
    ]
