# Generated by Django 3.2.20 on 2023-07-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0002_questao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaRealizadaPeloAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalizouAProva', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ava.aluno')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ava.prova')),
            ],
            options={
                'db_table': 'provas realizadas pelos alunos',
            },
        ),
        migrations.CreateModel(
            name='QuestaoDaProvaRealizadaPeloAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alternativaEscolhida', models.IntegerField()),
                ('acertouAQuestao', models.BooleanField(default=False)),
                ('provaRealizada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ava.provarealizadapeloaluno')),
            ],
            options={
                'db_table': 'questões das provas realizadas pelos alunos',
            },
        ),
    ]
