# Generated by Django 4.2.3 on 2023-07-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0002_prova_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nomeDoMaterial',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
