# Generated by Django 3.2.20 on 2023-08-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0002_auto_20230811_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissioes',
            options={'permissions': [('podeFazerProvas', 'aluno pode realizar a prova'), ('ehAdministrador', 'usuário logado é administrador'), ('ehAluno', 'usuário logado é aluno')]},
        ),
    ]
