# Generated by Django 3.2.20 on 2023-08-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0003_provarealizadapeloaluno_questaodaprovarealizadapeloaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaodaprovarealizadapeloaluno',
            name='questaoCorrespondente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ava.questao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questaodaprovarealizadapeloaluno',
            name='provaRealizada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.provarealizadapeloaluno'),
        ),
    ]
