# Generated by Django 3.2.20 on 2023-08-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0004_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
