# Generated by Django 3.2.20 on 2023-08-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0004_auto_20230801_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provarealizadapeloaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.aluno'),
        ),
        migrations.AlterField(
            model_name='provarealizadapeloaluno',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.prova'),
        ),
    ]
