# Generated by Django 4.2.3 on 2023-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0004_remove_material_rotadoanexo_material_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoRealizarProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('podeFazerAProva', 'aluno pode realizar a prova')],
            },
        ),
    ]
