# Generated by Django 3.2.20 on 2023-08-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0005_auto_20230803_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletimDeDesempenhoDoAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('aprovado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.materia')),
            ],
            options={
                'db_table': 'boletins de desempenho dos alunos',
            },
        ),
    ]
