# Generated by Django 3.2.20 on 2023-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0006_alter_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='notificacao',
            field=models.CharField(default='', max_length=510),
            preserve_default=False,
        ),
    ]
