# Generated by Django 4.2.3 on 2023-07-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0006_alter_material_anexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaorealizarprova',
            options={'permissions': [('podeFazerProvas', 'aluno pode realizar a prova')]},
        ),
    ]
