# Generated by Django 4.2.3 on 2023-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0007_alter_permissaorealizarprova_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='anexo',
            field=models.FileField(upload_to='src/media/diretorio/'),
        ),
    ]
