# Generated by Django 4.2.3 on 2023-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0008_alter_material_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='anexo',
            field=models.FileField(upload_to='anexos'),
        ),
    ]
